# Generated by Django 4.2.4 on 2023-08-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_nickname', models.CharField(max_length=20, verbose_name='고객 닉네임')),
                ('board_location', models.CharField(default='거래 희망 장소를 입력해주세요', max_length=60, verbose_name='고객 위치')),
                ('board_number', models.CharField(max_length=15, verbose_name='고객님 전화번호')),
                ('board_image', models.ImageField(null=True, upload_to='images/')),
                ('board_content', models.TextField(verbose_name='내용')),
                ('money', models.TextField(verbose_name='심부름 가격')),
                ('title', models.CharField(max_length=64, verbose_name='글 제목')),
                ('board_category', models.CharField(default='카테고리 등록해주세요', max_length=32, verbose_name='카테고리')),
                ('board_write_dttm', models.DateTimeField(auto_now=True, verbose_name='글 작성시간')),
                ('board_update_dttm', models.DateTimeField(auto_now=True, verbose_name='마지막 수정일')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
            ],
            options={
                'verbose_name': '게시판',
                'verbose_name_plural': '게시판',
                'db_table': 'Board',
            },
        ),
    ]
