# Generated by Django 4.2.4 on 2023-08-12 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('content', models.TextField(verbose_name='내용')),
                ('user_nickname', models.CharField(max_length=10, verbose_name='사용자 닉네임')),
                ('user_location', models.CharField(max_length=20, verbose_name='사용자 위치')),
                ('user_ph_number', models.CharField(max_length=15, verbose_name='전화번호')),
                ('title', models.CharField(max_length=64, verbose_name='글 제목')),
                ('board_name', models.CharField(default='물건', max_length=32, verbose_name='카테고리')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '게시판',
                'verbose_name_plural': '게시판',
                'db_table': 'Board',
            },
        ),
    ]
