# Generated by Django 4.2.4 on 2023-08-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_update_dttm',
            field=models.DateTimeField(auto_now=True, verbose_name='마지막 수정일'),
        ),
    ]
