# Generated by Django 4.2.4 on 2023-08-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_board_update_dttm'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='completion',
            field=models.BinaryField(default=False, verbose_name='완료여부'),
        ),
    ]
