# Generated by Django 4.2.4 on 2023-08-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_board_completion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='completion',
        ),
    ]
